# Generated by Django 3.0.7 on 2020-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(),
        ),
    ]
