# Generated by Django 3.0.7 on 2020-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200616_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='body_text',
            new_name='footer',
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
