# Generated by Django 3.0.7 on 2020-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200616_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='footer',
            field=models.TextField(blank=True),
        ),
    ]
