# Generated by Django 3.0.7 on 2020-06-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20200616_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='comments',
        ),
        migrations.AddField(
            model_name='email',
            name='title',
            field=models.CharField(default='Well', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
