# Generated by Django 3.0.7 on 2020-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_development', '0002_auto_20200710_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low'), ('5', '5 - Planning')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low'), ('5', '5 - Planning')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low'), ('5', '5 - Planning')], max_length=30, null=True),
        ),
    ]
