# Generated by Django 3.0.7 on 2020-07-10 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agile_development', '0004_auto_20200710_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='sys_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
