# Generated by Django 3.0.7 on 2020-07-13 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agile_development', '0005_auto_20200710_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumtask',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='storydependency',
            options={'verbose_name_plural': 'Story Dependencies'},
        ),
        migrations.AddField(
            model_name='feature',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='sys_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
