# Generated by Django 3.0.7 on 2020-07-13 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agile_development', '0006_auto_20200713_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumtask',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrumtask',
            name='sys_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='sys_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storydependency',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storydependency',
            name='sys_updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
