# Generated by Django 3.0.7 on 2020-07-19 07:56

import agile_development.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_development', '0007_auto_20200713_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='attached_image1',
            field=models.ImageField(blank=True, null=True, upload_to=agile_development.models.upload_path),
        ),
        migrations.AddField(
            model_name='story',
            name='attached_image2',
            field=models.ImageField(blank=True, null=True, upload_to=agile_development.models.upload_path),
        ),
        migrations.AddField(
            model_name='story',
            name='attached_image3',
            field=models.ImageField(blank=True, null=True, upload_to=agile_development.models.upload_path),
        ),
        migrations.AddField(
            model_name='story',
            name='attached_image4',
            field=models.ImageField(blank=True, null=True, upload_to=agile_development.models.upload_path),
        ),
        migrations.AddField(
            model_name='story',
            name='attached_image5',
            field=models.ImageField(blank=True, null=True, upload_to=agile_development.models.upload_path),
        ),
    ]
