# Generated by Django 3.0.7 on 2020-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_development', '0008_auto_20200719_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='attached_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
