# Generated by Django 3.0.7 on 2020-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_development', '0009_feature_attached_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready', 'Ready'), ('work in progress', 'Work in Progress'), ('ready for test', 'Ready for Testing'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
