# Generated by Django 3.0.7 on 2020-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_development', '0010_auto_20201102_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='read_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='read_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
