# Generated by Django 3.0.7 on 2020-06-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20200621_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m2m_knowledge_feedback_likes',
            old_name='commented_by',
            new_name='liked_by',
        ),
    ]
