# Generated by Django 3.0.7 on 2020-06-21 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0006_auto_20200621_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2m_knowledge_feedback_likes',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_knowledge_feedback_likes',
            unique_together={('comment', 'liked_by')},
        ),
    ]
