# Generated by Django 3.0.7 on 2020-07-01 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0007_auto_20200621_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kbuse',
            unique_together={('article', 'user')},
        ),
    ]
