# Generated by Django 3.0.7 on 2020-07-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_auto_20200701_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbuse',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.KbKnowledge'),
        ),
    ]
