# Generated by Django 3.0.7 on 2020-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_auto_20200701_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbknowledge',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/featured/'),
        ),
    ]
