# Generated by Django 3.0.7 on 2020-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_kbknowledge_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbknowledge',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article/featured_image_thumbs/'),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/featured_images/'),
        ),
    ]
