# Generated by Django 3.0.7 on 2020-07-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_auto_20200706_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='article_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='article_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.KbCategory'),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='workflow',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('retired', 'Retired'), ('outdated', 'Outdated')], max_length=10, null=True),
        ),
    ]
