# Generated by Django 3.0.7 on 2020-07-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_auto_20200706_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
