# Generated by Django 3.0.7 on 2020-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_bookmarkuserarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
