# Generated by Django 3.0.7 on 2020-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_auto_20200712_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbfeedback',
            name='comments',
            field=models.TextField(),
        ),
    ]
