# Generated by Django 3.0.7 on 2020-07-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_auto_20200713_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbfeedback',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.KbFeedback'),
        ),
    ]
