# Generated by Django 3.0.7 on 2020-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0020_kbknowledge_view_count_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbuse',
            name='useful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbuse',
            name='viewed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
