# Generated by Django 3.0.7 on 2020-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0021_auto_20200715_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbuse',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
