# Generated by Django 3.0.7 on 2020-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0023_auto_20200722_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbcategory',
            name='sys_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbcategory',
            name='sys_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledgebase',
            name='sys_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kbknowledgebase',
            name='sys_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
