# Generated by Django 3.0.7 on 2020-07-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0025_auto_20200723_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of_category', to='knowledge.KbCategory'),
        ),
    ]
