# Generated by Django 3.0.7 on 2020-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0026_auto_20200723_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='course',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kbcategory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kbcategory',
            name='section',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kbknowledge',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kbknowledgebase',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
