# Generated by Django 3.0.7 on 2020-07-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0027_auto_20200724_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='category',
            field=models.ForeignKey(default='random', on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='knowledge.KbCategory'),
        ),
        migrations.AlterField(
            model_name='kbknowledge',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_kb_base', to='knowledge.KbKnowledgeBase'),
        ),
    ]
