# Generated by Django 3.0.7 on 2020-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0028_auto_20200724_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
