# Generated by Django 3.0.7 on 2020-07-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0029_kbcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbuse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_kb_category', to='knowledge.KbFeedback'),
        ),
        migrations.AddField(
            model_name='kbuse',
            name='percentage_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
