# Generated by Django 3.0.7 on 2020-07-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0030_auto_20200727_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbuse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_kb_category', to='knowledge.KbCategory'),
        ),
    ]
