# Generated by Django 3.0.7 on 2020-07-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0031_auto_20200727_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbuse',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.KbKnowledge'),
        ),
    ]
