# Generated by Django 3.0.7 on 2020-09-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0036_auto_20200903_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
