# Generated by Django 3.0.7 on 2020-09-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0038_auto_20200903_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='knowledge.KnowledgeSection'),
        ),
    ]
