# Generated by Django 3.0.7 on 2020-10-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0040_auto_20200903_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbknowledge',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'course': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='knowledge.KbCategory'),
        ),
    ]
