# Generated by Django 3.0.7 on 2020-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0046_articletag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='relevance',
            field=models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Moderate'), ('3', 'Little')], max_length=10, null=True),
        ),
    ]
