# Generated by Django 3.0.7 on 2020-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0047_auto_20201102_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='relevance',
            field=models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Moderate'), ('3', 'Little')], default='2', max_length=10, null=True),
        ),
    ]
