# Generated by Django 3.0.7 on 2020-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0048_auto_20201103_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbknowledge',
            name='article_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
