# Generated by Django 3.0.7 on 2020-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0049_kbknowledge_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkuserarticle',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.KbCategory'),
        ),
    ]
