# Generated by Django 3.0.7 on 2020-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0050_bookmarkuserarticle_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='question_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='kbknowledgebase',
            name='question_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
