# Generated by Django 3.0.7 on 2021-03-30 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0051_auto_20201122_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbcategory',
            name='sys_created_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='Root Admin'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
