# Generated by Django 3.0.7 on 2020-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqanda', '0002_auto_20201113_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
