# Generated by Django 3.0.7 on 2020-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqanda', '0003_question_question_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
