# Generated by Django 3.0.7 on 2020-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqanda', '0005_auto_20201118_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
