# Generated by Django 3.0.7 on 2020-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqanda', '0007_auto_20201120_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='update_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='update_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
