# Generated by Django 3.0.7 on 2020-06-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0005_auto_20200616_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepient', models.EmailField(blank=True, max_length=50, null=True)),
                ('recepients', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Single Recepient', 'SR'), ('Multiple Recipient', 'MR')], default='SR', max_length=100)),
                ('email_body', models.TextField()),
                ('status', models.CharField(choices=[('Sent', '1'), ('Failed', '0')], max_length=10)),
                ('comments', models.TextField()),
                ('sys_created_on', models.DateTimeField(auto_now_add=True)),
                ('sys_updated_on', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.Email')),
            ],
        ),
    ]
