# Generated by Django 3.0.7 on 2020-06-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysemaillog',
            options={'verbose_name_plural': 'Email logs'},
        ),
        migrations.AlterField(
            model_name='sysemaillog',
            name='status',
            field=models.CharField(choices=[('1', 'Sent'), ('0', 'Failed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sysemaillog',
            name='type',
            field=models.CharField(choices=[('SR', 'Single Recipient'), ('MR', 'Multiple Recipient')], default='SR', max_length=2),
        ),
    ]
