# Generated by Django 3.0.7 on 2020-06-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200628_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysemaillog',
            old_name='recepient',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='sysemaillog',
            old_name='recepients',
            new_name='recipients',
        ),
    ]
