# Generated by Django 3.0.7 on 2020-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200628_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysemaillog',
            name='sent_from',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
