# Generated by Django 3.0.7 on 2020-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_sysemaillog_sent_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysemaillog',
            name='mail_sent_number',
            field=models.IntegerField(null=True),
        ),
    ]
