# Generated by Django 3.0.7 on 2020-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_sysemaillog_mail_sent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_created_on', models.DateTimeField(auto_now_add=True)),
                ('request_body', models.TextField(null=True)),
                ('request_header', models.TextField(null=True)),
                ('response_data', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('time_elapsed', models.DecimalField(decimal_places=4, max_digits=5)),
                ('function', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Request Logs',
            },
        ),
    ]
