# Generated by Django 3.0.7 on 2020-06-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20200629_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=4000)),
                ('source', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Random Logs',
            },
        ),
    ]
