# Generated by Django 3.0.7 on 2020-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20200629_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='time_elapsed',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
