# Generated by Django 3.0.7 on 2020-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20200705_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedimage',
            name='featured_image',
            field=models.BooleanField(default=False),
        ),
    ]
