# Generated by Django 3.0.7 on 2020-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20201030_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedimage',
            name='compressed_image_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attachedimage',
            name='real_image_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
