# Generated by Django 3.0.7 on 2020-10-30 11:57

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_auto_20201030_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedimage',
            name='compressed',
            field=models.ImageField(blank=True, null=True, upload_to=attachments.models.upload_path_compress),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='real_image',
            field=models.ImageField(upload_to=attachments.models.upload_path),
        ),
    ]
