# Generated by Django 3.0.7 on 2020-11-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_auto_20201030_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedimage',
            old_name='featured_image',
            new_name='flagged_image',
        ),
    ]
