# Generated by Django 3.0.7 on 2020-06-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0002_sysuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='profile',
        ),
    ]
