# Generated by Django 3.0.7 on 2020-06-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0002_sysuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
