# Generated by Django 3.0.7 on 2020-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0003_remove_sysuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
