# Generated by Django 3.0.7 on 2020-07-08 18:33

from django.db import migrations, models
import sys_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0003_sysuser_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=sys_user.models.upload_path),
        ),
    ]
