# Generated by Django 3.0.7 on 2020-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0004_sysuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
