# Generated by Django 3.0.7 on 2020-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0005_auto_20200708_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics_compressed'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
