# Generated by Django 3.0.7 on 2020-07-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0008_sysuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='user_type',
            field=models.CharField(choices=[('GU', 'GOOGLE'), ('RU', 'ROOT'), ('FU', 'FACEBOOK')], default='RU', max_length=2),
        ),
    ]
