# Generated by Django 3.0.7 on 2020-09-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0010_subscriptionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlist',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
