# Generated by Django 3.0.7 on 2020-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0011_auto_20200920_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='external_website_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='facebook_profile_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='instagram_profile_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='twitter_profile_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
