# Generated by Django 3.0.7 on 2020-11-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0012_auto_20200921_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='password_needs_reset',
            field=models.BooleanField(default=False),
        ),
    ]
